### ISSUE TITLE
`--preview` does not work

### ISSUE THREAD

**Issue by heyarne** [kimono-koans/httm#57] opened 2022-11-16 12:14 UTC
Love this utility, it's really neat! Unfortunately `--preview` doesn't seem to work? I just built 0.17.4 using a custom fork of `nixpkgs`, and running `httm --preview -s` looks like this:

![image](https://user-images.githubusercontent.com/525780/202177095-292b8c30-55e6-4ffc-8e75-bbc1f6312dbd.png)

Then after selecting a file that changed, this is the next screen:

![image](https://user-images.githubusercontent.com/525780/202177187-88b59101-adb3-4db8-98c4-c4f0916c7813.png)

As you can see, there's no diff shown. Could this be because of custom FZF settings? Other settings don't seem to influence the appearance of `httm` (I have a custom cursor for example), but maybe that's a potential source of bugs. I tried just `--preview` as well as custom commands (`--preview='delta {snap_file} {live_file}'` and `--preview='diff {snap_file} {live_file}'`), none seemed to work. Any idea why not?

PS: Maybe if no arguments are specified in `--preview`, assume that the command just takes arguments in `diff` order?

**Comment by kimono-koans** [comment] 2022-11-16 13:28
> Could this be because of custom FZF settings?

No, `httm` is not reliant upon `fzf`.  All facilities are native

1. First re: the bare `--preview`, could you check that you have `bowie` in your PATH?  
2. Second, could you try double quotes around your custom commands?  
3. Third, re: "I just built 0.17.4 using a custom fork of nixpkgs", how is it custom?  I'd advise trying to build from the original sources.  If, for instance, your `nix` package chooses not to install `bowie` and `ounce`, you won't be able to use the bare `--preview`.
4. Fourth, re: debugging, check your `sudo execsnoop-bpfcc -x -q` output.  I'd like to know what commands are executing when you take the steps above.
5. You have to be able to execute basic shell commands and built-ins (like `exec` and `cut`).  This could also be a `bash`-ism I've introduced?  Could you try running in a `bash` env? 

Nothing is immediately obvious as to what exactly your problem is.

**Comment by heyarne** [comment] 2022-11-16 14:21
I'm using fish 3.5.1, which I didn't mention in the original post.

1. Neither `ounce` nor `bowie` are in nixpkgs and I did not install them in any other way, so that probably explains the bare `--preview`. There is no error message however, is there any kind of verification done?
2. Just did that, same result
3. The fork just bumps the version, other than that it's the same as this package: https://github.com/NixOS/nixpkgs/blob/7d9bc072578398c148b667e7594300736bc09741/pkgs/tools/filesystems/httm/default.nix There's no reference to `bowie` or `ounce` as you can see.
4. Where do I get `execsnoop-bpfcc` from?
5. Same result.

**Comment by kimono-koans** [comment] 2022-11-16 14:51
My guess is that this is something `nix` specific in the way that it encapsulates the `httm` env.  And probably that, in combination with the non-portability of my base script, and a non-standard shell make this not work.

Re: bare `--preview`, the nix package is not installing the same this as the deb or rpm packaged versions.  You absolutely need `bowie` in your PATH.  Again, I'd build from source in a clean base environment, with all the tools found in the deb and rpm packages in your PATH.

Given that you have a heterodox environment (take your pick -- you're on an OS with a wonky layout, you're not using a package provided by me, and/or not using my steps to build from source), without more, this would be a WONTFIX as it stands right now.  That is -- you're going to have to do the extra leg work to run the exact issue to ground (or I'm not going to install `nix` just to figure it out) and *I hope you do*!  `execsnoop` could be really helpful here.  I know it is for me.  It prints the programs/scripts executed with arguments as they are executed on your system.  You can find it for `nix` here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/bpftrace/default.nix

*However*, I *will be* changing the base shell script to make it more portable/more error resistant, and to try to all the possible failure conditions fail with an error, and I *will open* a branch and provide you a link, so you can build from source, and see if this new script makes any difference for you.

Appreciate you filing this bug, pleased to work with you to resolve, but as indicated above, you're going to need to most of the hard stuff to root cause before I fix.  I hope you understand.  Thanks for filing the bug!  It will remain open.

**Comment by kimono-koans** [comment] 2022-11-16 22:02
https://github.com/kimono-koans/httm/releases/tag/0.17.5

**Comment by heyarne** [comment] 2022-11-18 07:30
Thank you very much for your information. I will see to look into this ASAP.

**Comment by kimono-koans** [comment] 2022-11-28 04:28
I am going to close this.  `bowie` is required to be installed, and I've tested personally with fish and it works.  Feel free to refile if/when your package includes `bowie` and you've installed a later versions with perhaps better errors about what is happened.  Thanks!

**Comment by kimono-koans** [comment] 2023-11-22 01:45
I'm closing again with this release: https://github.com/kimono-koans/httm/releases/tag/0.31.3

**Closed by kimono-koans** 2023-11-22 01:45 UTC
Labels: bug, good first issue, wontfix

**Comment by magnetophon** [comment] 2023-11-24 08:06
@heyarne In case you are still interested: version 0.31.5 works perfectly in NixOS using fish.
PR here: https://github.com/NixOS/nixpkgs/pull/267886
